/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DividendPayingTokenInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "dividendOf(address)": FunctionFragment;
    "withdrawDividend()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "dividendOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawDividend",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "dividendOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDividend",
    data: BytesLike
  ): Result;

  events: {
    "DividendWithdrawn(address,uint256)": EventFragment;
    "DividendsDistributed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DividendWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DividendsDistributed"): EventFragment;
}

export type DividendWithdrawnEvent = TypedEvent<
  [string, BigNumber] & { to: string; weiAmount: BigNumber }
>;

export type DividendsDistributedEvent = TypedEvent<
  [string, BigNumber] & { from: string; weiAmount: BigNumber }
>;

export class DividendPayingTokenInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DividendPayingTokenInterfaceInterface;

  functions: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    withdrawDividend(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  withdrawDividend(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdrawDividend(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "DividendWithdrawn(address,uint256)"(
      to?: string | null,
      weiAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { to: string; weiAmount: BigNumber }
    >;

    DividendWithdrawn(
      to?: string | null,
      weiAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { to: string; weiAmount: BigNumber }
    >;

    "DividendsDistributed(address,uint256)"(
      from?: string | null,
      weiAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; weiAmount: BigNumber }
    >;

    DividendsDistributed(
      from?: string | null,
      weiAmount?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { from: string; weiAmount: BigNumber }
    >;
  };

  estimateGas: {
    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    withdrawDividend(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    dividendOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawDividend(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
